In [11]:
%config IPCompleter.greedy=True

In [16]:
import pandas as pd
import os
dfo = os.path.join('D:/Dropbox/Coding/CompareExcel/Files/', '1234-401-001-- - Test-BOM.xlsx')
dfn = os.path.join('D:/Dropbox/Coding/CompareExcel/Files/', '1234-401-001-A - Test-BOM.xlsx')
df = os.path.join('C:/Working Folder/Designs/5-Projects/2500 - Aabenraa/Area 99 - Common Area/','2500-499-001-- - PARTLIST.xlsx')
df=pd.read_excel(df)

In [26]:
df.head()

,Item,Part Number,REV,Filename,Stock Number,Thumbnail,BOM Structure,Description,Material,Title,QTY,D,t,L,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,181,0000-710-001,-,2500-04.7-BM010-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN125-Ø140,0xSDR17 L=22190",PE100,NaN,1,140.0,8.2,22190.0,"PE100 Pipe - DN125-Ø140,0xSDR17","PE100 Pipe - DN125-Ø140,0xSDR17",933.938
1,172,0000-710-001,-,2500-04.7-BM007-02-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN200-Ø225,0xSDR11 L=22140",PE100,NaN,4,225.0,20.5,22140.0,"PE100 Pipe - DN200-Ø225,0xSDR11","PE100 Pipe - DN200-Ø225,0xSDR11",909.280
2,64,0000-710-002,-,2500-99-BG086-01-02.ipt,NaN,NaN,Normal,"PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26 L=287954",PE100,NaN,1,500.0,19.2,287954.0,"PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26","PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26",666.463
3,157,0000-710-001,-,2500-04.7-BM001-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN100-Ø125,0xSDR17 L=45794",PE100,NaN,1,125.0,7.4,45794.0,"PE100 Pipe - DN100-Ø125,0xSDR17","PE100 Pipe - DN100-Ø125,0xSDR17",634.570
4,104,0000-710-001,-,2500-99-BM040-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN250-Ø280,0xSDR17 L=49933",PE100,NaN,1,280.0,16.5,49933.0,"PE100 Pipe - DN250-Ø280,0xSDR17","PE100 Pipe - DN250-Ø280,0xSDR17",584.701

In [38]:
for t in df['Description']:
    tt=t.rsplit(' L=')[0]
    for t1 in tt:
        lt=

In [48]:
g=df.groupby(['Filename'])
g.head()

,Item,Part Number,REV,Filename,Stock Number,Thumbnail,BOM Structure,Description,Material,Title,QTY,D,t,L,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,181,0000-710-001,-,2500-04.7-BM010-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN125-Ø140,0xSDR17 L=22190",PE100,NaN,1,140.0,8.2,22190.0,"PE100 Pipe - DN125-Ø140,0xSDR17","PE100 Pipe - DN125-Ø140,0xSDR17",933.938
1,172,0000-710-001,-,2500-04.7-BM007-02-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN200-Ø225,0xSDR11 L=22140",PE100,NaN,4,225.0,20.5,22140.0,"PE100 Pipe - DN200-Ø225,0xSDR11","PE100 Pipe - DN200-Ø225,0xSDR11",909.280
2,64,0000-710-002,-,2500-99-BG086-01-02.ipt,NaN,NaN,Normal,"PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26 L=287954",PE100,NaN,1,500.0,19.2,287954.0,"PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26","PE100 Pipe - EN1555 - DN500-Ø500,0xSDR26",666.463
3,157,0000-710-001,-,2500-04.7-BM001-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN100-Ø125,0xSDR17 L=45794",PE100,NaN,1,125.0,7.4,45794.0,"PE100 Pipe - DN100-Ø125,0xSDR17","PE100 Pipe - DN100-Ø125,0xSDR17",634.570
4,104,0000-710-001,-,2500-99-BM040-01-01.ipt,NaN,NaN,Normal,"PE100 Pipe - DN250-Ø280,0xSDR17 L=49933",PE100,NaN,1,280.0,16.5,49933.0,"PE100 Pipe - DN250-Ø280,0xSDR17","PE100 Pipe - DN250-Ø280,0xSDR17",584.701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,202,0000-712-001,-,2500-01-TW120-02-02.ipt,NaN,NaN,Normal,"PE100 Pipe - DN32-Ø40,0xSDR17 L=95711",PE100,NaN,1,40.0,2.4,95711.0,NaN,NaN,NaN
187,203,0000-717-001,-,2500-01-TD069-01-01.ipt,NaN,NaN,Normal,"Drainage Pipe - Ø160,0 L=129665",PVC-Piping,NaN,1,160.0,5.7,129665.0,NaN,NaN,NaN
188,204,0000-717-041,-,Equal Y Junction 45° - Ø160 - PVC.ipt,NaN,NaN,Purchased,Equal Y Junction 45° - Ø160,PVC-Piping,NaN,11,NaN,"5,600 mm",NaN,NaN,NaN,NaN
189,205,0000-717-030,-,Socket Bend 45° - Ø160 - PVC.ipt,NaN,NaN,Purchased,Socket Bend 45° - Ø160,PVC-Piping,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN
190,206,0000-717-030,-,"Socket Bend 88,5° - Ø160 - PVC.ipt",NaN,NaN,Purchased,"Socket Bend 88,5° - Ø160",PVC-Piping,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN